### ISSUE TITLE
Multi port support

### ISSUE THREAD

**Issue by starsareintherose** [JabRef/JabRefOnline#379]
If my port 3000 is occupied, how can I run this program?

**Comment by mohit038** [comment]
You can define `PORT` as an environment variable in the `.env` file.

**Comment by starsareintherose** [comment]
such as `PORT=3360` ?

**Comment by starsareintherose** [comment]
my .env is here
```
[root@archlinux JabRefOnline]# cat .env
DATABASE_URL="postgresql://root:passwd@localhost:5432/jabref?schema=public"
PORT=3380
```
but it shows
````
[root@archlinux JabRefOnline]# yarn dev
yarn run v1.22.11
$ nuxt

 WARN  css-loader@3.6.0 is installed but >=4.2.0 is expected                                   23:34:30

ℹ Merging Tailwind config from ~/tailwind.config.js                           nuxt:tailwindcss 23:34:31

   ╭───────────────────────────────────────────────────────╮
   │                                                       │
   │   Nuxt @ v2.15.8                                      │
   │                                                       │
   │   ▸ Environment: development                          │
   │   ▸ Rendering:   client-side                          │
   │   ▸ Target:      server                               │
   │                                                       │
   │   Listening: http://localhost:3380/                   │
   │                                                       │
   │   Tailwind Viewer: http://localhost:3380/_tailwind/   │
   │                                                       │
   ╰───────────────────────────────────────────────────────╯

ℹ Preparing project for development                                                            23:34:33
ℹ Initial build may take a while                                                               23:34:33
node:events:371
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:6380
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1146:16)
Emitted 'error' event on RedisClient instance at:
    at RedisClient.on_error (/root/JabRefOnline/node_modules/redis/index.js:342:14)
    at Socket.<anonymous> (/root/JabRefOnline/node_modules/redis/index.js:223:14)
    at Socket.emit (node:events:394:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6380
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Siedlerchr** [comment]
You need to start redis as well

**Comment by starsareintherose** [comment]
I have used systemctl to start and enable redis, but it still shows that
```
[root@archlinux JabRefOnline]# yarn dev
yarn run v1.22.11
$ nuxt

 WARN  css-loader@3.6.0 is installed but >=4.2.0 is expected                                   01:34:57

ℹ Merging Tailwind config from ~/tailwind.config.js                           nuxt:tailwindcss 01:34:58

   ╭───────────────────────────────────────────────────────╮
   │                                                       │
   │   Nuxt @ v2.15.8                                      │
   │                                                       │
   │   ▸ Environment: development                          │
   │   ▸ Rendering:   client-side                          │
   │   ▸ Target:      server                               │
   │                                                       │
   │   Listening: http://localhost:3380/                   │
   │                                                       │
   │   Tailwind Viewer: http://localhost:3380/_tailwind/   │
   │                                                       │
   ╰───────────────────────────────────────────────────────╯

ℹ Preparing project for development                                                            01:35:00
ℹ Initial build may take a while                                                               01:35:00
node:events:371
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:6380
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1146:16)
Emitted 'error' event on RedisClient instance at:
    at RedisClient.on_error (/root/JabRefOnline/node_modules/redis/index.js:342:14)
    at Socket.<anonymous> (/root/JabRefOnline/node_modules/redis/index.js:223:14)
    at Socket.emit (node:events:394:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6380
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[root@archlinux JabRefOnline]# systemctl status redis
● redis.service - Advanced key-value store
     Loaded: loaded (/usr/lib/systemd/system/redis.service; enabled; vendor preset: disabled)
     Active: active (running) since Thu 2021-08-19 01:34:35 CST; 32s ago
```

**Comment by Siedlerchr** [comment]
in the package json I see that it uses a docker container to start redis on port 6300
https://github.com/JabRef/JabRefOnline/blob/08fd8d5e2ee3c7968f48d41568c6af6f6ecbe993/package.json#L26

**Comment by starsareintherose** [comment]
That's so sad, I must need to install docker

**Comment by starsareintherose** [comment]
Things seem okay, but the web shows `ERR_CONNECTION_REFUSED`
```
[root@archlinux JabRefOnline]# yarn dev
yarn run v1.22.11
$ nuxt

 WARN  css-loader@3.6.0 is installed but >=4.2.0 is expected                                   01:50:44

ℹ Merging Tailwind config from ~/tailwind.config.js                           nuxt:tailwindcss 01:50:44

   ╭───────────────────────────────────────────────────────╮
   │                                                       │
   │   Nuxt @ v2.15.8                                      │
   │                                                       │
   │   ▸ Environment: development                          │
   │   ▸ Rendering:   client-side                          │
   │   ▸ Target:      server                               │
   │                                                       │
   │   Listening: http://localhost:3380/                   │
   │                                                       │
   │   Tailwind Viewer: http://localhost:3380/_tailwind/   │
   │                                                       │
   ╰───────────────────────────────────────────────────────╯

ℹ Preparing project for development                                                            01:50:47
ℹ Initial build may take a while                                                               01:50:47
ℹ Discovered Components: .nuxt/components/readme.md                                            01:50:47
✔ Builder initialized                                                                          01:50:47
✔ Nuxt files generated                                                                         01:50:47

✔ Client
  Compiled successfully in 55.36s

ℹ Waiting for file changes                                                                     01:51:45
ℹ Memory usage: 500 MB (RSS: 733 MB)                                                           01:51:45
ℹ Listening on: http://localhost:3380/                                                         01:51:45
No issues found.                                                                               01:51:45


```

**Comment by Siedlerchr** [comment]
Did you init the postgres database?  That was my problem as well.
`Run yarn prisma:migrate:dev to initialize the database. You may also want to use yarn prisma:seed to fill the database with some initial test data.`

Then run and log in using the Test-User provided in the readme:
http://localhost:<PORT>/user/login

**Comment by starsareintherose** [comment]
I follow the readme, actually.
```
yarn install
yarn prisma:migrate:dev
yarn dev
```

**Comment by Siedlerchr** [comment]
run yarn prisma:seed to fill the database

**Comment by starsareintherose** [comment]
same error exsit

**Comment by tobiasdiez** [comment]
I don't really understand your last comment. It seems that the development server runs successfully on localhost. Not sure why you would expect it to run on your domain. Did you try to run jabref online on your server as well?
